//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Win32.rc
//
#define IDC_MYICON                      2
#define IDD_WIN32_DIALOG                102
#define IDD_ABOUTBOX                    103
#define IDS_APP_TITLE                   103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDS_HELLO                       106
#define IDI_WIN32                       107
#define IDI_SMALL                       108
#define IDC_WIN32                       109
#define IDS_STRING110                   110
#define IDS_STRING111                   111
#define IDS_STRING1                     112
#define IDS_STRING3                     113
#define IDS_STRING4                     114
#define IDS_STRING5                     115
#define IDS_STRING6                     116
#define IDS_STRING7                     117
#define IDS_STRING120                   120
#define IDS_STRING121                   121
#define IDS_STRING122                   122
#define IDS_STRING123                   123
#define IDS_STRING125                   125
#define IDR_MAINFRAME                   128
#define IDC_CURSOR1                     130
#define IDI_ICON1                       131
#define IDB_BITMAP1                     132
#define IDI_ICON2                       135
#define IDR_TOOLBAR1                    139
#define IDD_DIALOG2                     143
#define IDC_CURSOR2                     145
#define IDB_BITMAP2                     149
#define IDB_BITMAP3                     150
#define IDD_DIALOG1                     154
#define IDD_DIALOG3                     155
#define IDI_ICON3                       156
#define IDB_BITMAP4                     160
#define TrayIconPopup                   161
#define IDI_MAINICON                    169
#define IDI_SMALLICON                   176
#define IDD_DIALOG                      179
#define IDB_DELCROSS                    180
#define IDB_DELCROSS_                   181
#define IDD_KEYSET                      182
#define IDD_INPUT                       183
#define IDB_BATTY                       184
#define IDB_JUST                        185
#define IDD_INFO                        186
#define IDI_KEY                         188
#define IDD_TEXT                        189
#define BUTT                            1001
#define BUTT2                           1002
#define IDC_BUTTON2                     1023
#define IDC_BUTREM1                     1023
#define IDC_BUTREM2                     1024
#define IDC_ANIMAT1                     1030
#define IDC_SLIDER2                     1033
#define IDC_BUTTON1                     1034
#define IDC_CHECK1                      1035
#define IDC_ENCRCHECK1                  1035
#define IDC_RADIO1                      1036
#define IDC_RADIO1PL                    1036
#define IDC_STATIC1                     1037
#define IDC_RADIOSINGLE                 1037
#define IDC_RADIODOUBLE                 1038
#define IDC_RADIO2PL                    1039
#define IDC_SLIDER1                     1040
#define IDC_SLIDERMOUSE_L               1040
#define IDC_COMBO1                      1041
#define IDC_COMBO2                      1042
#define IDC_COMBO3                      1043
#define IDC_COMBO4                      1044
#define IDC_BUTPLAY                     1045
#define IDC_BUTNEWGAME                  1046
#define IDC_COMBO5                      1047
#define IDC_RADIOJOY_L                  1048
#define IDC_RADIOMOUSE_L                1049
#define IDC_RADIOKEY_L                  1050
#define IDC_BUTSET_L                    1051
#define IDC_RADIOJOY_R                  1052
#define IDC_RADIOMOUSE_R                1053
#define IDC_RADIOKEY_R                  1054
#define IDC_SHOW                        1055
#define IDC_BUTSET_R                    1056
#define IDC_SLIDERJOY_L                 1057
#define IDC_SLIDERJOY_R                 1058
#define IDC_SLIDERMOUSE_R               1059
#define IDC_STGAME                      1061
#define IDC_STLEVELS                    1062
#define IDC_STPLAYER_L                  1063
#define IDC_STCONTROLS_L                1064
#define IDC_STLOSTBALL_L                1065
#define IDC_STPRIZES_L                  1066
#define IDC_STBOMBS_L                   1067
#define IDC_STRATIO_L                   1068
#define IDC_STLEVPASSED                 1069
#define IDC_STPLAYER_R                  1070
#define IDC_STCONTROLS_R                1071
#define IDC_STLOSTBALL_R                1072
#define IDC_STPRIZES_R                  1073
#define IDC_STBOMBS_R                   1074
#define IDC_STRATIO_R                   1075
#define IDC_STTIMEPLAYED                1076
#define IDC_STLASTPLAYED                1077
#define IDC_ENCRCHECK2                  1078
#define IDC_SEPARATOR                   1079
#define IDC_STRBAT                      1080
#define IDC_STENCC                      1081
#define IDC_STGAM                       1082
#define IDC_HOTKEY1                     1083
#define IDC_STDIF                       1083
#define IDC_HOTKEY3                     1085
#define IDC_EDIT1                       1085
#define IDC_HOTKEY4                     1086
#define IDC_STATICF                     1086
#define IDC_EDIT2                       1086
#define IDC_HOTKEY5                     1087
#define IDC_EDIT3                       1087
#define IDC_HOTKEY6                     1088
#define IDC_EDIT4                       1088
#define IDC_STATICL                     1089
#define IDC_STATICR                     1090
#define IDC_STATICE                     1091
#define ID_BUTTON32771                  32771
#define IDM_SUCK                        32772
#define ID_BUTTON32772                  32772
#define IDM_FUCK                        32773
#define mnuAbout                        32773
#define iddd                            32775
#define ID_MENU2_ITEM1                  32776
#define ID_MENU2_ITEM2                  32777
#define ID_BUTTON32778                  32778
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        190
#define _APS_NEXT_COMMAND_VALUE         32779
#define _APS_NEXT_CONTROL_VALUE         1092
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
